name: Deploy PDFs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PDF for 1.1.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/reports/1.1.tex 

      - name: Build PDF for 1.2.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/reports/1.2.tex  

      - name: Build PDF for 2.0.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/reports/2.0.tex 

      - name: Build PDF for 3.0.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/reports/3.0.tex 

      - name: Move PDFs to output folder
        run: |
          mkdir -p compiled-pdfs
          mv 1.1.pdf compiled-pdfs/1.1.pdf 
          mv 1.2.pdf compiled-pdfs/1.2.pdf 
          mv 2.0.pdf compiled-pdfs/2.0.pdf 
          mv 3.0.pdf compiled-pdfs/3.0.pdf 

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: compiled-pdfs/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: compiled-pdfs
          target-folder: pdfs
